name: .NET

on:
  push:
    branches: [ dev-packageSigning ]
  pull_request:
    branches: [ dev-packageSigning ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Create Code Signing Certificate
      run : |
        New-Item -ItemType directory -Path certificate
        Set-Content -Path certificate\certificate.txt -Value '${{ secrets.CERTIFICATE }}'
        certutil -decode certificate\certificate.txt certificate\certificate.pfx
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Code Sign
      run : |
        & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x86/signtool.exe' sign /debug /f certificate\certificate.pfx /p '${{ secrets.CERTIFICATE_PASS }}' /t http://timestamp.comodoca.com/authenticode PgpCore\bin\Release\netstandard2.0\PgpCore.dll
    - name: Test
      run: dotnet test --no-build --verbosity normal
